### ISSUE TITLE
where i can store books ?

### ISSUE THREAD

**Issue by Mr-V3N0M** [bleedweedsuz/AndroidEbookViewer#1]
where i can store books ?

**Comment by bleedweedsuz** [comment]
we use firestore to store epub files.

**Comment by Mr-V3N0M** [comment]
can i see the firebase json backup file?

**Comment by bleedweedsuz** [comment]
Sry dude don't have any backup files. This project is discontinued. You don't need any Firebase system in this project to work with epub viewer you can use local path. I use this library [(epub.js)](https://github.com/futurepress/epub.js) to make main epub engine.
