### ISSUE TITLE
How can i show subheading of toc and zoom any image ?

### ISSUE THREAD

**Issue by Ramkesh9** [bleedweedsuz/AndroidEbookViewer#2]
Thank you for beautiful library, i used this and it help me a lot, but i am stuck at 2 points: 

1.)  can you let me know how can i show subheading in toc, (heading ( heading 1 ) are showing properly but sub heading are not (heading 2) ?

Like: 
chapter 1 
          - heading 1 
          - heading 2

chapter 2 : 
           - heading 1 
          - heading 2 
          - heading 3

2.) how can i get tap event on any specific image (i just want to zoom any image at tap or directy zoom webview for images) ?

please assist me to figure it out.

**Comment by bleedweedsuz** [comment]
sorry mate we no longer maintain this project so plz make an issue in epubjs project, their community will give you the proper answer. [epubjs](https://github.com/futurepress/epub.js/)

**Comment by Ramkesh9** [comment]
Ok Thank you to responding mate, 
Are you using referenced [library](https://github.com/futurepress/epub.js) in app code, or something else ? 
because referenced library contains huge numbers of files and you're using few limited files in android code, please clear my doubt ?

**Comment by bleedweedsuz** [comment]
First clone the project and compile, it will generate epub.min.js and you can only use that lib. 
If you want to open .epub file directly from your local device then use JSZip file to decompress the file.

You need node to compile the project, you can follow the instruction in their documentation.

Running Locally
install node.js

Then install the project dependences with npm
`npm install`

You can run the reader locally with the command
`npm start`

:source from https://github.com/futurepress/epub.js

for doc: http://epubjs.org/documentation/0.3/

**Comment by Ramkesh9** [comment]
Thank you for information, i will try to follow the guidelines and will check if i am able to do this.
