### ISSUE TITLE
access admin panel

### ISSUE THREAD

**Issue by AngleSmithTech** [bleedweedsuz/AndroidEbookViewer#3]
so i pulled your project it is well structured and very good bt how do you use the admin panel

**Comment by bleedweedsuz** [comment]
Sorry mate we don't maintain this project any more.
At that time we used Firebase hosting to upload different epub, pdf files.

If you are working on making epub viewer, look into [EPUB.JS](https://github.com/futurepress/epub.js/) documentation and use android Webview to display epub.js file. It is pretty simple to build in android.

Cheers

**Comment by bqytallhsirlkm** [comment]
it's a great app 
 how can I access to the admin panel??

**Comment by bleedweedsuz** [comment]
There is no Admin panel now (I lost the source code) but you can create your own using node.js or other server side scripting. At that time we used firebase as backend so maybe you can use firebase or other backend system. Or if you are interested on making epub.js viewer in android or Flutter or other lang [https://github.com/readium/awesome-readium](https://github.com/readium/awesome-readium)  use this link for reference.
